{$I MyLCL_SynEdit.inc}
{$I MyLCL_SynGutter.inc}
{$I MyLCL_SynCustomHighlighter.inc}
{$I MyLCL_SynCompletion.inc}
{$I MyLCL_SynAutoComplete.inc}
{$I MyLCL_SynHighlighterAttributes.inc}
{$I MyLCL_SynHighlighterPas.inc}
{$I MyLCL_SynHighlighterCpp.inc}
{$I MyLCL_SynHighlighterJava.inc}
{$I MyLCL_SynHighlighterJScript.inc}
{$I MyLCL_SynHighlighterHtml.inc}
{$I MyLCL_SynHighlighterXml.inc}
{$I MyLCL_SynHighlighterShell.inc}
{$I MyLCL_SynHighlighterCss.inc}
{$I MyLCL_SynHighlighterPhp.inc}
{$I MyLCL_SynHighlighterTex.inc}
{$I MyLCL_SynHighlighterSql.inc}
{$I MyLCL_SynHighlighterPython.inc}
{$I MyLCL_SynHighlighterBasic.inc}
{$I MyLCL_SynHighlighterBat.inc}

{$I MyLCL_SynAnySyn.inc}
