{$I MyLCL_Application.inc}  //BASECLASS:TComponent
{$I MyLCL_Form.inc}  //BASECLASS:TWinControl
{$I MyLCL_Button.inc}  //BASECLASS:TWinControl
{$I MyLCL_Edit.inc}  //BASECLASS:TWinControl
{$I MyLCL_MainMenu.inc}  //BASECLASS:TComponent
{$I MyLCL_PopupMenu.inc}  //BASECLASS:TComponent
{$I MyLCL_Memo.inc}  //BASECLASS:TWinControl
{$I MyLCL_CheckBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_RadioButton.inc}  //BASECLASS:TWinControl
{$I MyLCL_GroupBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_Label.inc}  //BASECLASS:TControl
{$I MyLCL_ListBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_ComboBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_Panel.inc}  //BASECLASS:TWinControl
{$I MyLCL_Image.inc}  //BASECLASS:TControl
{$I MyLCL_LinkLabel.inc}  //BASECLASS:TWinControl
{$I MyLCL_SpeedButton.inc}  //BASECLASS:TControl
{$I MyLCL_Splitter.inc}  //BASECLASS:TControl
{$I MyLCL_RadioGroup.inc}  //BASECLASS:TWinControl
{$I MyLCL_StaticText.inc}  //BASECLASS:TWinControl
{$I MyLCL_ColorBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_ColorListBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_TrayIcon.inc}  //BASECLASS:TComponent
{$I MyLCL_OpenDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_SaveDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_ColorDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_FontDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_PrintDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_OpenPictureDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_SavePictureDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_SelectDirectoryDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_RichEdit.inc}  //BASECLASS:TWinControl
{$I MyLCL_TrackBar.inc}  //BASECLASS:TWinControl
{$I MyLCL_ImageList.inc}  //BASECLASS:TComponent
{$I MyLCL_UpDown.inc}  //BASECLASS:TWinControl

{$I MyLCL_ProgressBar.inc}  //BASECLASS:TWinControl
{$I MyLCL_DateTimePicker.inc}  //BASECLASS:TWinControl
{$I MyLCL_MonthCalendar.inc}  //BASECLASS:TWinControl
{$I MyLCL_ListView.inc}  //BASECLASS:TWinControl
{$I MyLCL_TreeView.inc}  //BASECLASS:TWinControl
{$I MyLCL_StatusBar.inc}  //BASECLASS:TWinControl
{$I MyLCL_ToolBar.inc}  //BASECLASS:TWinControl
{$I MyLCL_BitBtn.inc}  //BASECLASS:TWinControl
{$I MyLCL_Icon.inc}  //BASECLASS:TGraphic
{$I MyLCL_Bitmap.inc}  //BASECLASS:TGraphic
{$I MyLCL_MemoryStream.inc}  //BASECLASS:TStream
{$I MyLCL_Font.inc}  //BASECLASS:TObject
{$I MyLCL_Strings.inc}  //BASECLASS:TStrings
{$I MyLCL_StringList.inc}  //BASECLASS:TStrings
{$I MyLCL_Brush.inc}  //BASECLASS:TObject
{$I MyLCL_Pen.inc}  //BASECLASS:TObject
{$I MyLCL_MenuItem.inc}  //BASECLASS:TComponent
{$I MyLCL_Picture.inc}  //BASECLASS:TObject
{$I MyLCL_ListColumns.inc}  //BASECLASS:TObject
{$I MyLCL_ListItems.inc}  //BASECLASS:TObject
{$I MyLCL_TreeNodes.inc}  //BASECLASS:TObject
{$I MyLCL_ListItem.inc}  //BASECLASS:TObject
{$I MyLCL_TreeNode.inc}  //BASECLASS:TObject
{$I MyLCL_PageControl.inc}  //BASECLASS:TWinControl
{$I MyLCL_TabSheet.inc}  //BASECLASS:TWinControl
{$I MyLCL_Control.inc}  //BASECLASS:TControl
{$I MyLCL_WinControl.inc}  //BASECLASS:TWinControl
{$I MyLCL_Screen.inc}  //BASECLASS:TComponent
{$I MyLCL_Mouse.inc}  //BASECLASS:TObject
{$I MyLCL_ListColumn.inc}  //BASECLASS:TObject
{$I MyLCL_CollectionItem.inc}  //BASECLASS:TObject
{$I MyLCL_StatusPanels.inc}  //BASECLASS:TObject
{$I MyLCL_StatusPanel.inc}  //BASECLASS:TObject
{$I MyLCL_SpinEdit.inc}  //BASECLASS:TWinControl
{$I MyLCL_FloatSpinEdit.inc}  //BASECLASS:TWinControl

{$I MyLCL_DirectoryEdit.inc}  //BASECLASS:TWinControl
{$I MyLCL_ColorButton.inc}  //BASECLASS:TControl
{$I MyLCL_MiniWebview.inc}  //BASECLASS:TWinControl
{$I MyLCL_Canvas.inc}  //BASECLASS:TObject
{$I MyLCL_Object.inc}  //BASECLASS:TObject
{$I MyLCL_Graphic.inc}  //BASECLASS:TGraphic
{$I MyLCL_PngImage.inc}  //BASECLASS:TGraphic
{$I MyLCL_JPEGImage.inc}  //BASECLASS:TGraphic
{$I MyLCL_GIFImage.inc}  //BASECLASS:TGraphic
{$I MyLCL_ActionList.inc}  //BASECLASS:TComponent
{$I MyLCL_Action.inc}  //BASECLASS:TComponent
{$I MyLCL_ToolButton.inc}  //BASECLASS:TControl
{$I MyLCL_IniFile.inc}  //BASECLASS:TObject
{$I MyLCL_Registry.inc}  //BASECLASS:TObject
{$I MyLCL_Clipboard.inc}  //BASECLASS:TObject
{$I MyLCL_Monitor.inc}  //BASECLASS:TObject
{$I MyLCL_PaintBox.inc}  //BASECLASS:TControl
{$I MyLCL_Timer.inc}  //BASECLASS:TComponent
{$I MyLCL_List.inc}  //BASECLASS:TObject
{$I MyLCL_Component.inc}  //BASECLASS:TComponent
{$I MyLCL_ParaAttributes.inc}  //BASECLASS:TObject
{$I MyLCL_TextAttributes.inc}  //BASECLASS:TObject
{$I MyLCL_IconOptions.inc}  //BASECLASS:TObject
{$I MyLCL_Exception.inc}  //BASECLASS:TObject
{$I MyLCL_ScrollBar.inc}  //BASECLASS:TWinControl
{$I MyLCL_MaskEdit.inc}  //BASECLASS:TWinControl
{$I MyLCL_Shape.inc}  //BASECLASS:TControl
{$I MyLCL_Bevel.inc}  //BASECLASS:TControl
{$I MyLCL_ScrollBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_CheckListBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_Gauge.inc}  //BASECLASS:TControl
{$I MyLCL_ImageButton.inc}  //BASECLASS:TControl
{$I MyLCL_FindDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_ReplaceDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_PrinterSetupDialog.inc}  //BASECLASS:TComponent

{$I MyLCL_PageSetupDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_DragObject.inc}  //BASECLASS:TObject
{$I MyLCL_DragDockObject.inc}  //BASECLASS:TObject
{$I MyLCL_StringGrid.inc}  //BASECLASS:TWinControl
{$I MyLCL_DrawGrid.inc}  //BASECLASS:TWinControl
{$I MyLCL_ValueListEditor.inc}  //BASECLASS:TWinControl
{$I MyLCL_HeaderControl.inc}  //BASECLASS:TWinControl
{$I MyLCL_HeaderSection.inc}  //BASECLASS:TObject
{$I MyLCL_HeaderSections.inc}  //BASECLASS:TObject
{$I MyLCL_LabeledEdit.inc}  //BASECLASS:TWinControl
{$I MyLCL_BoundLabel.inc}  //BASECLASS:TControl
{$I MyLCL_FlowPanel.inc}  //BASECLASS:TWinControl
{$I MyLCL_CoolBar.inc}  //BASECLASS:TWinControl
{$I MyLCL_CoolBands.inc}  //BASECLASS:TObject
{$I MyLCL_CoolBand.inc}  //BASECLASS:TObject
{$I MyLCL_Collection.inc}  //BASECLASS:TObject
{$I MyLCL_Printer.inc}  //BASECLASS:TObject
{$I MyLCL_TaskDialog.inc}  //BASECLASS:TComponent
{$I MyLCL_TaskDialogButtons.inc}  //BASECLASS:TObject
{$I MyLCL_TaskDialogButtonItem.inc}  //BASECLASS:TObject
{$I MyLCL_TaskDialogRadioButtonItem.inc}  //BASECLASS:TObject
{$I MyLCL_TaskDialogBaseButtonItem.inc}  //BASECLASS:TObject
{$I MyLCL_ComboBoxEx.inc}  //BASECLASS:TWinControl
{$I MyLCL_ComboExItems.inc}  //BASECLASS:TObject
{$I MyLCL_ComboExItem.inc}  //BASECLASS:TObject
{$I MyLCL_Frame.inc}  //BASECLASS:TWinControl
{$I MyLCL_ControlScrollBar.inc}  //BASECLASS:TObject
{$I MyLCL_SizeConstraints.inc}  //BASECLASS:TObject
{$I MyLCL_XButton.inc}  //BASECLASS:TControl
{$I MyLCL_AnchorSide.inc}  //BASECLASS:TObject
{$I MyLCL_ControlBorderSpacing.inc}  //BASECLASS:TObject
{$I MyLCL_ControlChildSizing.inc}  //BASECLASS:TObject
{$I MyLCL_CheckGroup.inc}  //BASECLASS:TWinControl
{$I MyLCL_ToggleBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_CheckComboBox.inc}  //BASECLASS:TWinControl
{$I MyLCL_GridColumnTitle.inc}  //BASECLASS:TObject
{$I MyLCL_GridColumn.inc}  //BASECLASS:TObject
{$I MyLCL_GridColumns.inc}  //BASECLASS:TObject

{$I MyLCL_SynEdit.inc}
{$I MyLCL_SynGutter.inc}
{$I MyLCL_SynCustomHighlighter.inc}
{$I MyLCL_SynCompletion.inc}
{$I MyLCL_SynAutoComplete.inc}
{$I MyLCL_SynHighlighterAttributes.inc}
{$I MyLCL_SynHighlighterPas.inc}
{$I MyLCL_SynHighlighterCpp.inc}
{$I MyLCL_SynHighlighterJava.inc}
{$I MyLCL_SynHighlighterJScript.inc}
{$I MyLCL_SynHighlighterHtml.inc}
{$I MyLCL_SynHighlighterXml.inc}
{$I MyLCL_SynHighlighterShell.inc}
{$I MyLCL_SynHighlighterCss.inc}
{$I MyLCL_SynHighlighterPhp.inc}
{$I MyLCL_SynHighlighterTex.inc}
{$I MyLCL_SynHighlighterSql.inc}
{$I MyLCL_SynHighlighterPython.inc}
{$I MyLCL_SynHighlighterBasic.inc}
{$I MyLCL_SynHighlighterBat.inc}
{$I MyLCL_SynAnySyn.inc}

{$I CEF_Global.inc}
{$I CEF_ChromeWindow.inc}
{$I CEF_Chrome.inc}

